import { randomUUID } from "crypto";
import { mkdir, writeFile } from "fs/promises";
import path from "path";

const DATA_DIR = path.join(process.cwd(), "data");

const rawItems = [
  // Tops
  {
    name: "Cream oxford shirt",
    category: "top",
    subcategory: "shirt",
    colors: ["#e5dac7"],
    pattern: "solid",
    formality: "business",
    warmth: 2,
    rainOk: false,
    seasons: ["spring", "fall"],
    occasionTags: ["work"],
    fit: "slim",
    favorite: false,
    photoUrl:
      "https://unsplash.com/photos/white-button-up-shirt-on-clothes-hanger-hMMXhKSZk7k/download",
  },
  {
    name: "Crisp white shirt",
    category: "top",
    subcategory: "shirt",
    colors: ["#ffffff"],
    pattern: "solid",
    formality: "business",
    warmth: 2,
    rainOk: false,
    seasons: ["spring", "summer", "fall"],
    occasionTags: ["work", "date"],
    fit: "slim",
    favorite: false,
  },
  {
    name: "Mustard chunky knit",
    category: "top",
    subcategory: "sweater",
    colors: ["#e2a63f"],
    pattern: "textured",
    formality: "casual",
    warmth: 4,
    rainOk: false,
    seasons: ["fall", "winter"],
    occasionTags: ["casual", "lounge"],
    fit: "relaxed",
    favorite: true,
  },
  {
    name: "Striped breton tee",
    category: "top",
    subcategory: "t-shirt",
    colors: ["#3a4a6b", "#ffffff"],
    pattern: "striped",
    formality: "casual",
    warmth: 1,
    rainOk: false,
    seasons: ["spring", "summer"],
    occasionTags: ["casual", "travel"],
    fit: "",
    favorite: false,
  },
  {
    name: "Graphic band tee",
    category: "top",
    subcategory: "t-shirt",
    colors: ["#241f1a"],
    pattern: "graphic",
    formality: "very_casual",
    warmth: 1,
    rainOk: false,
    seasons: ["summer"],
    occasionTags: ["casual", "lounge"],
    fit: "",
    favorite: false,
    photoUrl:
      "https://unsplash.com/photos/a-black-t-shirt-hangs-against-a-metal-grate-5gYpgixB9PE/download",
  },
  {
    name: "Sage silk blouse",
    category: "top",
    subcategory: "blouse",
    colors: ["#6f7d5c"],
    pattern: "solid",
    formality: "smart_casual",
    warmth: 1,
    rainOk: false,
    seasons: ["spring", "fall"],
    occasionTags: ["work", "date"],
    fit: "relaxed",
    favorite: true,
  },

  // Bottoms
  {
    name: "Charcoal wool trousers",
    category: "bottom",
    subcategory: "trousers",
    colors: ["#55493f"],
    pattern: "solid",
    formality: "business",
    warmth: 3,
    rainOk: false,
    seasons: ["fall", "winter"],
    occasionTags: ["work"],
    fit: "tailored",
    favorite: false,
  },
  {
    name: "Straight leg denim",
    category: "bottom",
    subcategory: "jeans",
    colors: ["#5b7ea0"],
    pattern: "solid",
    formality: "casual",
    warmth: 2,
    rainOk: false,
    seasons: ["spring", "fall"],
    occasionTags: ["casual", "travel"],
    fit: "straight",
    favorite: false,
    photoUrl: "https://unsplash.com/photos/pile-of-blue-denim-jeans-lot-UP9DtTjRYpI/download",
  },
  {
    name: "Black tailored trousers",
    category: "bottom",
    subcategory: "trousers",
    colors: ["#241f1a"],
    pattern: "solid",
    formality: "smart_casual",
    warmth: 2,
    rainOk: false,
    seasons: ["spring", "fall", "winter"],
    occasionTags: ["work", "date"],
    fit: "tailored",
    favorite: false,
  },
  {
    name: "Black leggings",
    category: "bottom",
    subcategory: "leggings",
    colors: ["#241f1a"],
    pattern: "solid",
    formality: "very_casual",
    warmth: 2,
    rainOk: false,
    seasons: ["spring", "summer", "fall"],
    occasionTags: ["gym", "lounge"],
    fit: "",
    favorite: false,
  },
  {
    name: "Khaki chinos",
    category: "bottom",
    subcategory: "chinos",
    colors: ["#8b5a2b"],
    pattern: "solid",
    formality: "casual",
    warmth: 2,
    rainOk: false,
    seasons: ["spring", "summer", "fall"],
    occasionTags: ["casual", "travel", "outdoor"],
    fit: "straight",
    favorite: false,
    photoUrl:
      "https://unsplash.com/photos/a-man-in-a-white-shirt-and-khaki-pants-DjniaF8q-HI/download",
  },

  // Dresses
  {
    name: "Burgundy wrap dress",
    category: "dress",
    subcategory: "wrap dress",
    colors: ["#7d2e46"],
    pattern: "solid",
    formality: "smart_casual",
    warmth: 2,
    rainOk: false,
    seasons: ["fall", "spring"],
    occasionTags: ["date", "party"],
    fit: "",
    favorite: true,
    photoUrl:
      "https://unsplash.com/photos/black-sleeveless-top-hanging-on-wardrobe-cp-VMJ-mdKs/download",
  },
  {
    name: "Floral midi dress",
    category: "dress",
    subcategory: "midi dress",
    colors: ["#e5dac7", "#7d2e46"],
    pattern: "floral",
    formality: "casual",
    warmth: 1,
    rainOk: false,
    seasons: ["spring", "summer"],
    occasionTags: ["casual", "date"],
    fit: "",
    favorite: false,
  },

  // Outerwear
  {
    name: "Navy wool coat",
    category: "outerwear",
    subcategory: "coat",
    colors: ["#3a4a6b"],
    pattern: "solid",
    formality: "business",
    warmth: 5,
    rainOk: true,
    seasons: ["fall", "winter"],
    occasionTags: ["work", "travel"],
    fit: "tailored",
    favorite: false,
    photoUrl:
      "https://unsplash.com/photos/a-jacket-hanging-on-a-coat-rack-in-a-room-C1-PIlyLvD8/download",
  },
  {
    name: "Sage rain jacket",
    category: "outerwear",
    subcategory: "jacket",
    colors: ["#6f7d5c"],
    pattern: "solid",
    formality: "casual",
    warmth: 3,
    rainOk: true,
    seasons: ["spring", "fall"],
    occasionTags: ["outdoor", "travel", "casual"],
    fit: "",
    favorite: false,
  },
  {
    name: "Black leather jacket",
    category: "outerwear",
    subcategory: "jacket",
    colors: ["#241f1a"],
    pattern: "solid",
    formality: "smart_casual",
    warmth: 3,
    rainOk: false,
    seasons: ["fall", "spring"],
    occasionTags: ["casual", "date", "party"],
    fit: "",
    favorite: true,
    photoUrl: "https://unsplash.com/photos/man-wearing-black-leather-jacket-TsfEeRp_j48/download",
  },
  {
    name: "Cream cardigan",
    category: "outerwear",
    subcategory: "cardigan",
    colors: ["#e5dac7"],
    pattern: "textured",
    formality: "casual",
    warmth: 3,
    rainOk: false,
    seasons: ["spring", "fall"],
    occasionTags: ["casual", "lounge"],
    fit: "relaxed",
    favorite: false,
  },

  // Shoes
  {
    name: "Leather derby shoes",
    category: "shoes",
    subcategory: "derby",
    colors: ["#241f1a"],
    pattern: "solid",
    formality: "business",
    warmth: 2,
    rainOk: false,
    seasons: ["fall", "winter", "spring"],
    occasionTags: ["work"],
    fit: "",
    favorite: false,
    photoUrl: "https://unsplash.com/photos/pair-of-brown-leather-dress-shoes-OuxPfti70I0/download",
  },
  {
    name: "Suede sneakers",
    category: "shoes",
    subcategory: "sneakers",
    colors: ["#c1592e"],
    pattern: "solid",
    formality: "casual",
    warmth: 1,
    rainOk: false,
    seasons: ["spring", "summer"],
    occasionTags: ["casual"],
    fit: "",
    favorite: false,
  },
  {
    name: "White sneakers",
    category: "shoes",
    subcategory: "sneakers",
    colors: ["#ffffff"],
    pattern: "solid",
    formality: "casual",
    warmth: 1,
    rainOk: false,
    seasons: ["spring", "summer", "fall"],
    occasionTags: ["casual", "travel", "outdoor"],
    fit: "",
    favorite: false,
    photoUrl:
      "https://unsplash.com/photos/a-pair-of-white-sneakers-on-a-white-background-8GzbKs74yq4/download",
  },
  {
    name: "Ankle boots",
    category: "shoes",
    subcategory: "boots",
    colors: ["#8b5a2b"],
    pattern: "solid",
    formality: "smart_casual",
    warmth: 3,
    rainOk: true,
    seasons: ["fall", "winter"],
    occasionTags: ["date", "work", "travel"],
    fit: "",
    favorite: false,
  },
  {
    name: "Running shoes",
    category: "shoes",
    subcategory: "trainers",
    colors: ["#9a9a9a"],
    pattern: "solid",
    formality: "very_casual",
    warmth: 1,
    rainOk: false,
    seasons: ["spring", "summer", "fall"],
    occasionTags: ["gym", "outdoor"],
    fit: "",
    favorite: false,
  },

  // Accessories
  {
    name: "Wool scarf",
    category: "accessory",
    subcategory: "scarf",
    colors: ["#e2a63f"],
    pattern: "textured",
    formality: "casual",
    warmth: 4,
    rainOk: false,
    seasons: ["fall", "winter"],
    occasionTags: ["casual", "work", "travel"],
    fit: "",
    favorite: false,
  },
  {
    name: "Leather belt",
    category: "accessory",
    subcategory: "belt",
    colors: ["#8b5a2b"],
    pattern: "solid",
    formality: "business",
    warmth: 1,
    rainOk: false,
    seasons: ["spring", "summer", "fall", "winter"],
    occasionTags: ["work", "date"],
    fit: "",
    favorite: false,
    photoUrl:
      "https://unsplash.com/photos/a-close-up-of-a-leather-belt-on-a-bench-Mf194wsFKZI/download",
  },
  {
    name: "Canvas tote bag",
    category: "accessory",
    subcategory: "bag",
    colors: ["#e5dac7"],
    pattern: "solid",
    formality: "casual",
    warmth: 1,
    rainOk: false,
    seasons: ["spring", "summer", "fall", "winter"],
    occasionTags: ["work", "travel", "casual"],
    fit: "",
    favorite: false,
  },
];

function toClosetItem(raw) {
  const now = new Date().toISOString();
  return {
    id: randomUUID(),
    createdAt: now,
    updatedAt: now,
    notes: "",
    ...raw,
  };
}

const closet = rawItems.map(toClosetItem);

const today = {
  date: new Date().toISOString().slice(0, 10),
  city: "Amsterdam, North Holland, Netherlands",
  latitude: 52.3676,
  longitude: 4.9041,
  plans: [
    {
      id: randomUUID(),
      title: "Client presentation",
      time: "10:00",
      occasionTag: "work",
    },
    {
      id: randomUUID(),
      title: "Dinner with friends",
      time: "19:30",
      occasionTag: "date",
    },
  ],
  moodChips: ["professional"],
  moodNote: "Want to go straight from the office to dinner without changing.",
};

const settings = {
  city: "Amsterdam, North Holland, Netherlands",
  latitude: 52.3676,
  longitude: 4.9041,
};

await mkdir(DATA_DIR, { recursive: true });
await writeFile(
  path.join(DATA_DIR, "closet.json"),
  JSON.stringify(closet, null, 2),
);
await writeFile(
  path.join(DATA_DIR, "today.json"),
  JSON.stringify(today, null, 2),
);
await writeFile(
  path.join(DATA_DIR, "settings.json"),
  JSON.stringify(settings, null, 2),
);

console.log(`Seeded ${closet.length} closet items, a sample day, and settings.`);
console.log("Note: weather is not pre-filled — hit \"Check weather\" on the Today page to pull it live.");
